from . import common
from . import test_multi_company
from . import test_attendance_activity
from . import test_attendance_device_user
from . import test_finger_template
from . import test_hr_employee
from . import test_mock_attendance_device
from . import test_mock_device_connection
from . import test_hr_attendance
