# -*- coding: utf-8 -*-
from . import res_company
from . import res_currency
from . import res_config_settings
from . import account_move
from . import account_move_line
from . import account_partial_reconcile
from . import account_report
from . import account_partner_ledger
from . import account_aged_partner_balance
from . import account_general_ledger
from . import account_journal_report
from . import account_generic_tax_report
from . import account_cash_flow_report
from . import account_payment
from . import product_template
from . import product_product
from . import purchase_order
from . import stock_landed_cost
from . import stock_landed_cost_lines
from . import stock_valuation_adjustment_lines
from . import stock_valuation_layer
from . import account_journal_dashboard
from . import stock_picking
from . import product_template_attribute_value
from . import reconciliation_widget
from . import account_asset
from . import account_assets_report
from . import account_bank_statement
from . import account_bank_statement_line
from . import account_analytic_account
from . import account_analytic_line
